DP pt.2 feat: add main service
Nuuvik/java-explore-with-me pull request #5
Opened 2023-10-14 12:10 UTC by Nuuvik

2023-10-14 18:32 UTC, kalitva requested changes

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/controller/PrivateEventController.java
> +@RequestMapping(path = "/users")
Можно `/{userId}` сюда перенести

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/dao/CategoriesMainServiceRepository.java
> +    @Query("select cat " +
А зачем запрос, просто `List<Categories> findAll(Pageable pageable);` не будет работать?

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/dao/CompilationMainServiceRepository.java
> +            "where com.pinned = ?1 or (com.pinned = false or com.pinned = true) ")
`"where com.pinned = :pinned or ...`

Всегда избегай индексов когда можно указать параметр по имени

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/dao/EventMainServiceRepository.java
> +
Лишняя пустая линия

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/exception/ErrorResponse.java
> +    public ErrorResponse(String status, String reason, String message, String timestamp) {
`AllArgsConstructor`?

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/mapper/CategoriesMapper.java
> +    public List<CategoriesDto> toListCategoriesDto(List<Categories> list) {
`toListCategoriesDto -- >toCategoriesDto`

Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/mapper/CompilationMapper.java
> +    public List<CompilationsDto> toListCompilationDto(List<CompilationShort> list) {
Тоже `toListCompilationDto --> toCompilationsDto`

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/AdminCategoriesServiceImpl.java
> +            throw new ConflictException("Нельзя удалить категорию с ивентами");
Сообщение в исключениях только по английски, иначе можео получить в логах что-то типа `????? ???????? ??`

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/AdminCategoriesServiceImpl.java
> +
Удали лишние пустые линии

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/AdminEventService.java
> +    List<Event> getAdminEvents(List<Long> users, List<State> states, List<Long> categories, LocalDateTime rangeStart, LocalDateTime rangeEnd, int from, int size);
Многовато параметров. Оптимально количество параметров метода - 1 или 2, 3 уже много, больше - плохо (исключение - методы спринговых контроллеров). Подумай как можно сократить количество параметров, например использовать Parameter Object паттерн https://www.baeldung.com/spring-enum-request-param#clone

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/AdminEventServiceImpl.java
> +        Event event = repository.findById(eventId).orElseThrow(() -> new NotFoundException("События " + eventId + " не найденно"));
Давай это все по английски

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/PrivateEventServiceImpl.java
> +        boolean answer = repository.existsByIdAndInitiatorId(eventId, userId);
`answer` - не очень хорошое имя для этой переменной. Давай лучше вообще заинлайним ее (ctrl + alt + n)

2023-10-14 18:32 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/service/UserServiceImpl.java
> +@Transactional(readOnly = true)
Лучше укажи ее над `getUsers`

2023-10-14 18:32 UTC, kalitva commented on ewm-stat-service/stat_service/src/main/java/ru/practicum/service/StatServiceImpl.java
> +            } else { //если не надо учитывать уникальность
Удали эти комменты, здесь без них несложно разобраться

2023-10-16 11:07 UTC, Nuuvik commented on ewm-main-service/src/main/java/ru/practicum/main/dao/CategoriesMainServiceRepository.java
> +    @Query("select cat " +
попробовал без запроса - не работает :(

2023-10-16 18:09 UTC, kalitva approved these changes

2023-10-16 18:09 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/controller/AdminCategoriesController.java
> +@RequestMapping(path = "/admin")
`/admin --> /admin/categories`

2023-10-16 18:09 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/controller/UserController.java
> +        List<AdminUserDto> list = UserMapper.toListAdminUserDto(userService.getUsers(ids, from, size));
Нам действительно нужна эта переменная? Верни  сразу выражение

2023-10-16 18:09 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/dao/CategoriesMainServiceRepository.java
> +    @Query("select cat " +
`findAll` пробовал или `findAllCategories`?

2023-10-16 18:09 UTC, kalitva commented on ewm-main-service/src/main/java/ru/practicum/main/exception/ErrorResponse.java
> +
Лишние пустые линии

2023-10-25 09:12 UTC, merged